Issue_497 - Plugin-Module is calculated incorrectly
jenkinsci/plugin-compat-tester pull request #557
Opened 2023-06-01 13:18 UTC by ampuscas

Related to https://github.com/jenkinsci/maven-hpi-plugin/issues/497 

### Testing done

### Submitter checklist

- [ ] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [ ] Ensure that the pull request title represents the desired changelog entry
- [ ] Please describe what you did
- [ ] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue

2023-06-01 13:39 UTC, jtnord requested changes
https://github.com/jenkinsci/plugin-compat-tester/blob/master/src/main/java/org/jenkins/tools/test/model/plugin_metadata/Plugin.java#L84-L90

As a result of this change the Javadoc (and annotation) is no longer true and we will always have a module.

2023-06-01 13:39 UTC, jtnord commented on src/main/java/org/jenkins/tools/test/model/plugin_metadata/LegacyPluginMetadataExtractor.java
> +                .withModule(model.getArtifactId())
this would be is incorrect and should be

```suggestion
                .withModule(":" + model.getArtifactId())
```

2023-06-05 09:41 UTC, jtnord commented
[`LocalCheckoutPluginMetadataExtractor`](https://github.com/jenkinsci/plugin-compat-tester/blob/9d7ff9c73839a61c7de49227994d84ddd78791df/src/main/java/org/jenkins/tools/test/model/plugin_metadata/LocalCheckoutPluginMetadataExtractor.java#L45-L70) should probably be updated to also use `:pluginId`

2023-06-05 15:04 UTC, basil commented
Seems fine I guess. I did not test this in BOM.

2023-06-05 15:56 UTC, jtnord approved these changes

2023-06-06 10:50 UTC, merged